"""initial schema

Revision ID: 33e7fa4cc73b
Revises: 
Create Date: 2026-09-07 15:21:43.771413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e7fa4cc73b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amc_recovery_records',
    sa.Column('serial_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('registration_no', sa.String(length=50), nullable=True),
    sa.Column('imei', sa.String(length=50), nullable=True),
    sa.Column('vehicle_status', sa.String(length=50), nullable=True),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('res_phone', sa.String(length=50), nullable=True),
    sa.Column('office_phone', sa.String(length=50), nullable=True),
    sa.Column('cell1', sa.String(length=50), nullable=True),
    sa.Column('cell2', sa.String(length=50), nullable=True),
    sa.Column('is_defaulter', sa.Boolean(), nullable=True),
    sa.Column('secondary_user1', sa.String(length=50), nullable=True),
    sa.Column('secondary_user2', sa.String(length=50), nullable=True),
    sa.Column('secondary_user3', sa.String(length=50), nullable=True),
    sa.Column('secondary_user4', sa.String(length=50), nullable=True),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('receivable_amount', sa.Float(), nullable=True),
    sa.Column('received_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('from_year', sa.String(length=10), nullable=True),
    sa.Column('to_year', sa.String(length=10), nullable=True),
    sa.Column('payment_type', sa.String(length=50), nullable=True),
    sa.Column('transaction_id', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('cheque_number', sa.String(length=50), nullable=True),
    sa.Column('bank', sa.String(length=100), nullable=True),
    sa.Column('collection_date', sa.DateTime(), nullable=True),
    sa.Column('collected_by', sa.String(length=100), nullable=True),
    sa.Column('last_gps_at', sa.DateTime(), nullable=True),
    sa.Column('last_gps_address', sa.String(length=300), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('amc_recovery_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_amc_recovery_records_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_amc_recovery_records_registration_no'), ['registration_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_amc_recovery_records_serial_id'), ['serial_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_amc_recovery_records_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('cities',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('corporate_vehicles',
    sa.Column('registration_no', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.String(length=50), nullable=True),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('fleet_size', sa.Integer(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corporate_vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corporate_vehicles_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_corporate_vehicles_registration_no'), ['registration_no'], unique=True)

    op.create_table('current_locations',
    sa.Column('device_imei', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.String(length=20), nullable=True),
    sa.Column('lng', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('speed', sa.String(length=10), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('current_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_current_locations_device_imei'), ['device_imei'], unique=True)

    op.create_table('device_types',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('inventory_stock_items',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('total_received', sa.Float(), nullable=True),
    sa.Column('total_issued', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'category', 'period', name='uq_stock_item_name_category_period')
    )
    with op.batch_alter_table('inventory_stock_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_stock_items_period'), ['period'], unique=False)

    op.create_table('petrol_rates',
    sa.Column('rate_per_liter', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovery_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovery_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cell1', sa.String(length=50), nullable=True),
    sa.Column('employee_name', sa.String(length=200), nullable=True),
    sa.Column('total_amc_charges', sa.Float(), nullable=True),
    sa.Column('total_recovered', sa.Float(), nullable=True),
    sa.Column('total_lost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_recipients',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_recipients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_recipients_email'), ['email'], unique=True)

    op.create_table('technicians',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('home_lat', sa.String(length=20), nullable=True),
    sa.Column('home_lng', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_code_sequence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_code', sa.String(length=20), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('additional_roles', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('last_login_day', sa.Date(), nullable=True),
    sa.Column('last_late_login', sa.Date(), nullable=True),
    sa.Column('late_login_streak', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_name', sa.String(length=100), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_user_code'), ['user_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('vehicle_colors',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vehicle_makes',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vehicle_registry',
    sa.Column('sj_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('registration_no', sa.String(length=50), nullable=False),
    sa.Column('imei_no', sa.String(length=50), nullable=True),
    sa.Column('sim_no', sa.String(length=50), nullable=True),
    sa.Column('engine_no', sa.String(length=50), nullable=True),
    sa.Column('chassis_no', sa.String(length=50), nullable=True),
    sa.Column('unit_location', sa.String(length=200), nullable=True),
    sa.Column('vehicle_status', sa.String(length=50), nullable=True),
    sa.Column('manufacturer', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('model_year', sa.String(length=10), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('transmission', sa.String(length=20), nullable=True),
    sa.Column('power_cc', sa.String(length=20), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_mobile', sa.String(length=50), nullable=True),
    sa.Column('cell1', sa.String(length=50), nullable=True),
    sa.Column('cell2', sa.String(length=50), nullable=True),
    sa.Column('res_phone', sa.String(length=50), nullable=True),
    sa.Column('office_phone', sa.String(length=50), nullable=True),
    sa.Column('secondary_users', sa.String(length=300), nullable=True),
    sa.Column('last_signal_at', sa.DateTime(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_registry_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_registry_imei_no'), ['imei_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_registry_manufacturer'), ['manufacturer'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_registry_registration_no'), ['registration_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_registry_sim_no'), ['sim_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_registry_sj_vehicle_id'), ['sj_vehicle_id'], unique=True)

    op.create_table('vehicle_years',
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year')
    )
    op.create_table('amc_database_assignments',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('match_day', sa.Integer(), nullable=False),
    sa.Column('match_month', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('registration_no', sa.String(length=50), nullable=True),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('outstanding_amount', sa.Float(), nullable=True),
    sa.Column('assigned_officer_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('work_status', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['amc_recovery_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_no', 'due_date', name='uq_amc_db_assignment_vehicle_due_date')
    )
    with op.batch_alter_table('amc_database_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_amc_database_assignments_assigned_officer_id'), ['assigned_officer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_amc_database_assignments_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_amc_database_assignments_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_amc_database_assignments_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_amc_database_assignments_registration_no'), ['registration_no'], unique=False)

    op.create_table('fuel_reimbursement_invoices',
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_distance', sa.Float(), nullable=True),
    sa.Column('total_fuel_liters', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('petrol_rate_applied', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('inventory_devices',
    sa.Column('gs_object_id', sa.String(length=50), nullable=True),
    sa.Column('imei', sa.String(length=50), nullable=False),
    sa.Column('sim_number', sa.String(length=50), nullable=True),
    sa.Column('device_name', sa.String(length=200), nullable=True),
    sa.Column('plate_number', sa.String(length=50), nullable=True),
    sa.Column('dt_server', sa.DateTime(), nullable=True),
    sa.Column('dt_tracker', sa.DateTime(), nullable=True),
    sa.Column('gs_last_update', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_technician_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('installed_registration_no', sa.String(length=50), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_technician_id'], ['technicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_devices_gs_object_id'), ['gs_object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_devices_imei'), ['imei'], unique=True)
        batch_op.create_index(batch_op.f('ix_inventory_devices_status'), ['status'], unique=False)

    op.create_table('non_reporting_vehicles',
    sa.Column('registration_no', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_contact', sa.String(length=50), nullable=True),
    sa.Column('customer_phone2', sa.String(length=50), nullable=True),
    sa.Column('customer_phone3', sa.String(length=50), nullable=True),
    sa.Column('emergency_mobile', sa.String(length=50), nullable=True),
    sa.Column('emergency_name', sa.String(length=100), nullable=True),
    sa.Column('res_phone', sa.String(length=50), nullable=True),
    sa.Column('office_phone', sa.String(length=50), nullable=True),
    sa.Column('imei_no', sa.String(length=50), nullable=True),
    sa.Column('sim_no', sa.String(length=50), nullable=True),
    sa.Column('make', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('engine_no', sa.String(length=100), nullable=True),
    sa.Column('chassis_no', sa.String(length=100), nullable=True),
    sa.Column('vehicle_year', sa.String(length=4), nullable=True),
    sa.Column('vehicle_color', sa.String(length=20), nullable=True),
    sa.Column('device_location', sa.String(length=200), nullable=True),
    sa.Column('unit_location', sa.String(length=200), nullable=True),
    sa.Column('dt_tracker', sa.DateTime(), nullable=True),
    sa.Column('dt_server', sa.DateTime(), nullable=True),
    sa.Column('lat', sa.String(length=20), nullable=True),
    sa.Column('lng', sa.String(length=20), nullable=True),
    sa.Column('speed', sa.String(length=20), nullable=True),
    sa.Column('last_reporting_time', sa.DateTime(), nullable=True),
    sa.Column('first_detected_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('contact_outcome', sa.String(length=50), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('last_contact_date', sa.DateTime(), nullable=True),
    sa.Column('next_followup_date', sa.Date(), nullable=True),
    sa.Column('issue_summary', sa.Text(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('technician_notes', sa.Text(), nullable=True),
    sa.Column('device_imei', sa.String(length=50), nullable=True),
    sa.Column('device_sim', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('non_reporting_vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_non_reporting_vehicles_registration_no'), ['registration_no'], unique=True)

    op.create_table('purchase_orders',
    sa.Column('po_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('owner_name', sa.String(length=200), nullable=False),
    sa.Column('owner_contact', sa.String(length=50), nullable=False),
    sa.Column('contact_person_driver', sa.String(length=200), nullable=True),
    sa.Column('reg_no', sa.String(length=50), nullable=False),
    sa.Column('vehicle_make', sa.String(length=50), nullable=False),
    sa.Column('vehicle_model', sa.String(length=50), nullable=False),
    sa.Column('vehicle_year', sa.String(length=4), nullable=False),
    sa.Column('vehicle_color', sa.String(length=20), nullable=False),
    sa.Column('engine_number', sa.String(length=100), nullable=False),
    sa.Column('chassis_number', sa.String(length=100), nullable=False),
    sa.Column('transmission', sa.String(length=20), nullable=True),
    sa.Column('power_cc', sa.String(length=20), nullable=True),
    sa.Column('sales_person_id', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('vehicle_availability_location', sa.String(length=200), nullable=False),
    sa.Column('existing_customer_name', sa.String(length=200), nullable=True),
    sa.Column('existing_vehicle_number', sa.String(length=100), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('technician_assigned', sa.String(length=100), nullable=True),
    sa.Column('imei_no', sa.String(length=50), nullable=True),
    sa.Column('sim_no', sa.String(length=50), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('device_location', sa.String(length=200), nullable=True),
    sa.Column('fuel', sa.String(length=50), nullable=True),
    sa.Column('tested_by', sa.String(length=100), nullable=True),
    sa.Column('arranged_by_sales_person', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('completion_email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('rates', sa.Float(), nullable=True),
    sa.Column('amc', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_name', sa.String(length=100), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sales_person_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_po_number'), ['po_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_purchase_orders_reg_no'), ['reg_no'], unique=False)

    op.create_table('recovery_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('reg_no', sa.String(length=100), nullable=True),
    sa.Column('installation_date', sa.String(length=50), nullable=True),
    sa.Column('installation_year', sa.String(length=10), nullable=True),
    sa.Column('amc_charges', sa.Float(), nullable=True),
    sa.Column('recovered_amount', sa.Float(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('sheet_name', sa.String(length=100), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['recovery_clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_vehicles', schema=None) as batch_op:
        batch_op.create_index('idx_rec_vehicles_reg_no', ['reg_no'], unique=False)
        batch_op.create_index('idx_rec_vehicles_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_vehicles_reg_no'), ['reg_no'], unique=False)

    op.create_table('redo_activities',
    sa.Column('redo_number', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('rates', sa.String(length=50), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_contact', sa.String(length=50), nullable=True),
    sa.Column('sale_person', sa.String(length=100), nullable=True),
    sa.Column('arranged_by', sa.String(length=100), nullable=True),
    sa.Column('previous_customer', sa.String(length=200), nullable=True),
    sa.Column('registration_no', sa.String(length=50), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('chassis_no', sa.String(length=100), nullable=True),
    sa.Column('engine_no', sa.String(length=100), nullable=True),
    sa.Column('old_vehicle', sa.String(length=100), nullable=True),
    sa.Column('imei_no', sa.String(length=50), nullable=True),
    sa.Column('sim_no', sa.String(length=50), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('device_location', sa.String(length=200), nullable=True),
    sa.Column('old_imei_no', sa.String(length=50), nullable=True),
    sa.Column('old_sim_no', sa.String(length=50), nullable=True),
    sa.Column('new_device', sa.String(length=50), nullable=True),
    sa.Column('new_sim', sa.String(length=50), nullable=True),
    sa.Column('device_change_reason', sa.String(length=50), nullable=True),
    sa.Column('technician', sa.String(length=100), nullable=True),
    sa.Column('tested_by', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('vehicle_location', sa.String(length=200), nullable=True),
    sa.Column('transfer_installation', sa.String(length=10), nullable=True),
    sa.Column('transfer_charges', sa.String(length=50), nullable=True),
    sa.Column('fuel', sa.String(length=50), nullable=True),
    sa.Column('resolution_status', sa.String(length=30), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('rework_reason', sa.Text(), nullable=True),
    sa.Column('issue_description', sa.Text(), nullable=True),
    sa.Column('previous_installation_notes', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('rework_completed_date', sa.Date(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('redo_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_redo_activities_redo_number'), ['redo_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_redo_activities_registration_no'), ['registration_no'], unique=False)

    op.create_table('removal_retained_activities',
    sa.Column('registration_no', sa.String(length=50), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('chassis_no', sa.String(length=100), nullable=True),
    sa.Column('engine_no', sa.String(length=100), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_contact', sa.String(length=50), nullable=True),
    sa.Column('imei_no', sa.String(length=50), nullable=True),
    sa.Column('sim_no', sa.String(length=50), nullable=True),
    sa.Column('device_location', sa.String(length=200), nullable=True),
    sa.Column('removal_reason', sa.Text(), nullable=True),
    sa.Column('removal_date', sa.Date(), nullable=True),
    sa.Column('removal_type', sa.String(length=50), nullable=True),
    sa.Column('device_returned', sa.Boolean(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('device_condition', sa.String(length=100), nullable=True),
    sa.Column('retained_by', sa.String(length=100), nullable=True),
    sa.Column('storage_location', sa.String(length=200), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('removal_retained_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_removal_retained_activities_registration_no'), ['registration_no'], unique=False)

    op.create_table('removal_transfer_activities',
    sa.Column('old_registration_no', sa.String(length=50), nullable=False),
    sa.Column('old_make', sa.String(length=50), nullable=True),
    sa.Column('old_model', sa.String(length=50), nullable=True),
    sa.Column('old_year', sa.String(length=4), nullable=True),
    sa.Column('old_color', sa.String(length=20), nullable=True),
    sa.Column('old_chassis_no', sa.String(length=100), nullable=True),
    sa.Column('old_engine_no', sa.String(length=100), nullable=True),
    sa.Column('old_customer_name', sa.String(length=200), nullable=True),
    sa.Column('old_customer_contact', sa.String(length=50), nullable=True),
    sa.Column('old_imei_no', sa.String(length=50), nullable=True),
    sa.Column('old_sim_no', sa.String(length=50), nullable=True),
    sa.Column('old_device_location', sa.String(length=200), nullable=True),
    sa.Column('new_registration_no', sa.String(length=50), nullable=False),
    sa.Column('new_make', sa.String(length=50), nullable=True),
    sa.Column('new_model', sa.String(length=50), nullable=True),
    sa.Column('new_year', sa.String(length=4), nullable=True),
    sa.Column('new_color', sa.String(length=20), nullable=True),
    sa.Column('new_chassis_no', sa.String(length=100), nullable=True),
    sa.Column('new_engine_no', sa.String(length=100), nullable=True),
    sa.Column('new_customer_name', sa.String(length=200), nullable=True),
    sa.Column('new_customer_contact', sa.String(length=50), nullable=True),
    sa.Column('transfer_reason', sa.Text(), nullable=True),
    sa.Column('device_transferred_date', sa.Date(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('removal_transfer_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_removal_transfer_activities_old_registration_no'), ['old_registration_no'], unique=False)

    op.create_table('suggestions',
    sa.Column('reference', sa.String(length=30), nullable=False),
    sa.Column('raised_by', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('handled_by', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['handled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suggestions_raised_by'), ['raised_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestions_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_suggestions_status'), ['status'], unique=False)

    op.create_table('technician_bikes',
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('imei', sa.String(length=50), nullable=False),
    sa.Column('bike_registration', sa.String(length=50), nullable=False),
    sa.Column('bike_model', sa.String(length=100), nullable=True),
    sa.Column('fuel_efficiency', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imei'),
    sa.UniqueConstraint('technician_id')
    )
    op.create_table('technician_stock_issuances',
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('technician_id', 'issue_date', name='uq_tech_issuance_technician_date')
    )
    with op.batch_alter_table('technician_stock_issuances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technician_stock_issuances_issue_date'), ['issue_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_technician_stock_issuances_technician_id'), ['technician_id'], unique=False)

    op.create_table('user_notifications',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('vehicle_flags',
    sa.Column('registration_no', sa.String(length=50), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('chassis_no', sa.String(length=100), nullable=True),
    sa.Column('engine_no', sa.String(length=100), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_contact', sa.String(length=50), nullable=True),
    sa.Column('imei_no', sa.String(length=50), nullable=True),
    sa.Column('sim_no', sa.String(length=50), nullable=True),
    sa.Column('device_location', sa.String(length=200), nullable=True),
    sa.Column('flag_reason', sa.Text(), nullable=False),
    sa.Column('flag_type', sa.String(length=50), nullable=False),
    sa.Column('flagged_by', sa.Integer(), nullable=True),
    sa.Column('flagged_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['flagged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_flags_registration_no'), ['registration_no'], unique=False)

    op.create_table('vehicle_models',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('make_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['make_id'], ['vehicle_makes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_logs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amc_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=60), nullable=False),
    sa.Column('basis', sa.String(length=10), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('vehicle_count', sa.Integer(), nullable=False),
    sa.Column('sheet_names', sa.String(length=300), nullable=True),
    sa.Column('total_charges', sa.Float(), nullable=False),
    sa.Column('total_received', sa.Float(), nullable=False),
    sa.Column('outstanding_amount', sa.Float(), nullable=False),
    sa.Column('invoiced_amount', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('discount_reason', sa.String(length=300), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['recovery_clients.id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['recovery_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('amc_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_amc_invoices_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_amc_invoices_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_amc_invoices_generated_by'), ['generated_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_amc_invoices_invoice_number'), ['invoice_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_amc_invoices_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('complaints',
    sa.Column('ticket_no', sa.String(length=30), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_contact', sa.String(length=50), nullable=False),
    sa.Column('reg_no', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('vehicle_location', sa.String(length=200), nullable=True),
    sa.Column('complaint_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_name', sa.String(length=100), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaints_reg_no'), ['reg_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_ticket_no'), ['ticket_no'], unique=True)

    op.create_table('fuel_invoice_expenses',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('added_by_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['fuel_reimbursement_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fuel_invoice_expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuel_invoice_expenses_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('installation_recovery_charges',
    sa.Column('redo_activity_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_officer_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('proof_of_payment_path', sa.String(length=255), nullable=True),
    sa.Column('recovered_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['redo_activity_id'], ['redo_activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('installation_recovery_charges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installation_recovery_charges_redo_activity_id'), ['redo_activity_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_installation_recovery_charges_status'), ['status'], unique=False)

    op.create_table('live_amc_assignments',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('match_day', sa.Integer(), nullable=False),
    sa.Column('match_month', sa.Integer(), nullable=False),
    sa.Column('assigned_officer_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('work_status', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['recovery_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id', 'due_date', name='uq_live_amc_vehicle_due_date')
    )
    with op.batch_alter_table('live_amc_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_amc_assignments_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_amc_assignments_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('non_reporting_conversations',
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('conversation_date', sa.DateTime(), nullable=True),
    sa.Column('conversation_type', sa.String(length=20), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_number', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('recorded_by_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['non_reporting_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_recovery',
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('total_rates', sa.Float(), nullable=True),
    sa.Column('total_amc', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('amount_received', sa.Float(), nullable=True),
    sa.Column('remaining_amount', sa.Float(), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('payment_due_date', sa.Date(), nullable=True),
    sa.Column('payment_received_date', sa.Date(), nullable=True),
    sa.Column('payment_received_by', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('proof_of_payment_path', sa.String(length=255), nullable=True),
    sa.Column('cheque_number', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('recovery_notes', sa.Text(), nullable=True),
    sa.Column('last_follow_up', sa.Date(), nullable=True),
    sa.Column('next_follow_up', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payment_received_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_id')
    )
    op.create_table('recovery_followups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('next_date', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['recovery_clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['recovery_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovery_history_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('payment_date', sa.String(length=50), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('cheque_status', sa.String(length=50), nullable=True),
    sa.Column('proof_of_payment_path', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['recovery_clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['recovery_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_briefing_data',
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('segment', sa.String(length=50), nullable=True),
    sa.Column('cnic', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('father_name', sa.String(length=200), nullable=True),
    sa.Column('mother_name', sa.String(length=200), nullable=True),
    sa.Column('secondary_user_name', sa.String(length=200), nullable=True),
    sa.Column('secondary_user_phone', sa.String(length=50), nullable=True),
    sa.Column('emergency_user_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_user_phone', sa.String(length=50), nullable=True),
    sa.Column('device_serial_no', sa.String(length=100), nullable=True),
    sa.Column('sim_network', sa.String(length=100), nullable=True),
    sa.Column('accessories_installed', sa.String(length=500), nullable=True),
    sa.Column('password_1', sa.String(length=100), nullable=True),
    sa.Column('password_2', sa.String(length=100), nullable=True),
    sa.Column('fence', sa.String(length=500), nullable=True),
    sa.Column('security_training_completed', sa.Boolean(), nullable=True),
    sa.Column('customer_demonstration', sa.Boolean(), nullable=True),
    sa.Column('services_explained', sa.Boolean(), nullable=True),
    sa.Column('customer_signature', sa.Text(), nullable=True),
    sa.Column('acknowledgement', sa.Boolean(), nullable=True),
    sa.Column('briefed_by', sa.String(length=100), nullable=True),
    sa.Column('briefed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('officer_notes', sa.Text(), nullable=True),
    sa.Column('synced_from_po', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_id')
    )
    op.create_table('suggestion_messages',
    sa.Column('suggestion_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('from_admin', sa.Boolean(), nullable=False),
    sa.Column('status_change', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['suggestion_id'], ['suggestions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suggestion_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suggestion_messages_suggestion_id'), ['suggestion_id'], unique=False)

    op.create_table('technician_trips',
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('imei', sa.String(length=50), nullable=True),
    sa.Column('trip_order', sa.Integer(), nullable=True),
    sa.Column('start_lat', sa.String(length=20), nullable=True),
    sa.Column('start_lng', sa.String(length=20), nullable=True),
    sa.Column('start_address', sa.String(length=500), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_lat', sa.String(length=20), nullable=True),
    sa.Column('end_lng', sa.String(length=20), nullable=True),
    sa.Column('end_address', sa.String(length=500), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('fuel_used_liters', sa.Float(), nullable=True),
    sa.Column('fuel_cost', sa.Float(), nullable=True),
    sa.Column('petrol_rate_at_time', sa.Float(), nullable=True),
    sa.Column('previous_trip_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('installation_recovery_followups',
    sa.Column('charge_id', sa.Integer(), nullable=False),
    sa.Column('conversation_date', sa.DateTime(), nullable=True),
    sa.Column('conversation_type', sa.String(length=20), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_number', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('recorded_by_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['charge_id'], ['installation_recovery_charges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('installation_recovery_followups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installation_recovery_followups_charge_id'), ['charge_id'], unique=False)

    op.create_table('payment_history',
    sa.Column('payment_recovery_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payment_recovery_id'], ['payment_recovery.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_history')
    with op.batch_alter_table('installation_recovery_followups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installation_recovery_followups_charge_id'))

    op.drop_table('installation_recovery_followups')
    op.drop_table('technician_trips')
    with op.batch_alter_table('suggestion_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggestion_messages_suggestion_id'))

    op.drop_table('suggestion_messages')
    op.drop_table('security_briefing_data')
    op.drop_table('recovery_history_records')
    op.drop_table('recovery_followups')
    op.drop_table('payment_recovery')
    op.drop_table('non_reporting_conversations')
    with op.batch_alter_table('live_amc_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_amc_assignments_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_live_amc_assignments_due_date'))

    op.drop_table('live_amc_assignments')
    with op.batch_alter_table('installation_recovery_charges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installation_recovery_charges_status'))
        batch_op.drop_index(batch_op.f('ix_installation_recovery_charges_redo_activity_id'))

    op.drop_table('installation_recovery_charges')
    with op.batch_alter_table('fuel_invoice_expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuel_invoice_expenses_invoice_id'))

    op.drop_table('fuel_invoice_expenses')
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaints_ticket_no'))
        batch_op.drop_index(batch_op.f('ix_complaints_reg_no'))

    op.drop_table('complaints')
    with op.batch_alter_table('amc_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_amc_invoices_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_amc_invoices_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_amc_invoices_generated_by'))
        batch_op.drop_index(batch_op.f('ix_amc_invoices_created_at'))
        batch_op.drop_index(batch_op.f('ix_amc_invoices_client_id'))

    op.drop_table('amc_invoices')
    op.drop_table('activity_logs')
    op.drop_table('vehicle_models')
    with op.batch_alter_table('vehicle_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_flags_registration_no'))

    op.drop_table('vehicle_flags')
    with op.batch_alter_table('user_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_notifications_is_read'))

    op.drop_table('user_notifications')
    with op.batch_alter_table('technician_stock_issuances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technician_stock_issuances_technician_id'))
        batch_op.drop_index(batch_op.f('ix_technician_stock_issuances_issue_date'))

    op.drop_table('technician_stock_issuances')
    op.drop_table('technician_bikes')
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggestions_status'))
        batch_op.drop_index(batch_op.f('ix_suggestions_reference'))
        batch_op.drop_index(batch_op.f('ix_suggestions_raised_by'))

    op.drop_table('suggestions')
    with op.batch_alter_table('removal_transfer_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_removal_transfer_activities_old_registration_no'))

    op.drop_table('removal_transfer_activities')
    with op.batch_alter_table('removal_retained_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_removal_retained_activities_registration_no'))

    op.drop_table('removal_retained_activities')
    with op.batch_alter_table('redo_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_redo_activities_registration_no'))
        batch_op.drop_index(batch_op.f('ix_redo_activities_redo_number'))

    op.drop_table('redo_activities')
    with op.batch_alter_table('recovery_vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_vehicles_reg_no'))
        batch_op.drop_index('idx_rec_vehicles_status')
        batch_op.drop_index('idx_rec_vehicles_reg_no')

    op.drop_table('recovery_vehicles')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_reg_no'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_po_number'))

    op.drop_table('purchase_orders')
    with op.batch_alter_table('non_reporting_vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_non_reporting_vehicles_registration_no'))

    op.drop_table('non_reporting_vehicles')
    with op.batch_alter_table('inventory_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_devices_status'))
        batch_op.drop_index(batch_op.f('ix_inventory_devices_imei'))
        batch_op.drop_index(batch_op.f('ix_inventory_devices_gs_object_id'))

    op.drop_table('inventory_devices')
    op.drop_table('fuel_reimbursement_invoices')
    with op.batch_alter_table('amc_database_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_amc_database_assignments_registration_no'))
        batch_op.drop_index(batch_op.f('ix_amc_database_assignments_record_id'))
        batch_op.drop_index(batch_op.f('ix_amc_database_assignments_due_date'))
        batch_op.drop_index(batch_op.f('ix_amc_database_assignments_client_id'))
        batch_op.drop_index(batch_op.f('ix_amc_database_assignments_assigned_officer_id'))

    op.drop_table('amc_database_assignments')
    op.drop_table('vehicle_years')
    with op.batch_alter_table('vehicle_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_registry_sj_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_registry_sim_no'))
        batch_op.drop_index(batch_op.f('ix_vehicle_registry_registration_no'))
        batch_op.drop_index(batch_op.f('ix_vehicle_registry_manufacturer'))
        batch_op.drop_index(batch_op.f('ix_vehicle_registry_imei_no'))
        batch_op.drop_index(batch_op.f('ix_vehicle_registry_client_id'))

    op.drop_table('vehicle_registry')
    op.drop_table('vehicle_makes')
    op.drop_table('vehicle_colors')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_user_code'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('user_code_sequence')
    op.drop_table('technicians')
    with op.batch_alter_table('report_recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_recipients_email'))

    op.drop_table('report_recipients')
    op.drop_table('recovery_clients')
    op.drop_table('recovery_audit_logs')
    op.drop_table('petrol_rates')
    with op.batch_alter_table('inventory_stock_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_stock_items_period'))

    op.drop_table('inventory_stock_items')
    op.drop_table('device_types')
    with op.batch_alter_table('current_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_current_locations_device_imei'))

    op.drop_table('current_locations')
    with op.batch_alter_table('corporate_vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corporate_vehicles_registration_no'))
        batch_op.drop_index(batch_op.f('ix_corporate_vehicles_client_id'))

    op.drop_table('corporate_vehicles')
    op.drop_table('cities')
    with op.batch_alter_table('amc_recovery_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_amc_recovery_records_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_amc_recovery_records_serial_id'))
        batch_op.drop_index(batch_op.f('ix_amc_recovery_records_registration_no'))
        batch_op.drop_index(batch_op.f('ix_amc_recovery_records_client_id'))

    op.drop_table('amc_recovery_records')
    # ### end Alembic commands ###
