; deployment/supervisor/celery.conf
[program:celery]
command=/usr/bin/celery -A src.tasks.celery_app worker --loglevel=info --concurrency=4
directory=/var/www/on_track
user=www-data
autostart=true
autorestart=true
startretries=3
stderr_logfile=/var/log/on_track/celery.err.log
stdout_logfile=/var/log/on_track/celery.out.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=10

[program:celery-beat]
command=/usr/bin/celery -A src.tasks.celery_app beat --loglevel=info
directory=/var/www/on_track
user=www-data
autostart=true
autorestart=true
startretries=3
stderr_logfile=/var/log/on_track/celery-beat.err.log
stdout_logfile=/var/log/on_track/celery-beat.out.log 
