; deployment/supervisor/gunicorn.conf
[program:on_track]
command=/usr/bin/gunicorn -c /var/www/on_track/deployment/gunicorn.conf.py wsgi:app
directory=/var/www/on_track
user=www-data
autostart=true
autorestart=true
startretries=3
stderr_logfile=/var/log/on_track/gunicorn.err.log
stdout_logfile=/var/log/on_track/gunicorn.out.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=10
environment=FLASK_ENV="production",DATABASE_URL="postgresql://on_track:password@localhost/on_track_db"